name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COLUMNS: "120"
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  lint:
    name: Static analysis
    uses: antonagestam/goose/.github/workflows/run.yaml@0.11.0

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@main

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
          check-latest: true
          allow-prereleases: true
      - run: pip install -e '.[test]'
      - run: pytest
